#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK
#
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2024 Qais Yousef

import argparse
import freq
import idle
import matplotlib
import matplotlib.pyplot as pltlib
import os
import plotext as pltext
import sa_track
import sched
import settings
import trace_processor as tp
import utils

try:
    import argcomplete
except:
    pass

args = None


def parse_cmdline():
    parser = argparse.ArgumentParser(description='''
    Post Process sched-analyzer.perfetto-trace captured with sched-analyzer tool
    ''', formatter_class=argparse.RawTextHelpFormatter)

    parser.add_argument('filename',
                    help='perfetto-trace file to post process.')

    parser.add_argument('--save-png', action='store_true',
                    help='Save graphs as png images.')
    parser.add_argument('--save-csv', action='store_true',
                    help='Save raw data as csv file.')

    parser.add_argument('--freq', action='store_true',
                    help='Show frequency for all cpus.')
    parser.add_argument('--freq-residency', action='store_true',
                    help='Show percentage of time spent in each frequency for all cpus.')
    parser.add_argument('--freq-task', action='append', metavar='PATTERN',
                    help='Show frequency for a given task')
    parser.add_argument('--freq-residency-task', action='append', metavar='PATTERN',
                    help='Show frequency residency for a given task')
    parser.add_argument('--idle-residency', action='store_true',
                    help='Show percentage of time spent in each idle state for all cpus.')

    parser.add_argument('--util-avg', action='append', metavar='PATTERN',
                    help='Show util_avg for CPUs/tasks. Can be provided multiple times. \'CPU\' to show all cpus or specific task name to show all task that match the str')
    parser.add_argument('--util-avg-hist', action='append', metavar='PATTERN',
                    help='Same as util-avg but shows a histogram instead.')
    parser.add_argument('--util-avg-rt', action='append', metavar='PATTERN',
                    help='Show util_avg_rt for CPUs. Can be provided multiple times. \'CPU\' to show all cpus')
    parser.add_argument('--util-avg-rt-hist', action='append', metavar='PATTERN',
                    help='Same as util-avg-rt but shows a histogram instead.')
    parser.add_argument('--util-avg-dl', action='append', metavar='PATTERN',
                    help='Show util_avg_dl for CPUs. Can be provided multiple times. \'CPU\' to show all cpus')
    parser.add_argument('--util-avg-dl-hist', action='append', metavar='PATTERN',
                    help='Same as util-avg-dl but shows a histogram instead.')
    parser.add_argument('--util-avg-irq', action='append', metavar='PATTERN',
                    help='Show util_avg_irq for CPUs. Can be provided multiple times. \'CPU\' to show all cpus')
    parser.add_argument('--util-avg-irq-hist', action='append', metavar='PATTERN',
                    help='Same as util-avg-irq but shows a histogram instead.')
    parser.add_argument('--load-avg-thermal', action='append', metavar='PATTERN',
                    help='Show load_avg_thermal for CPUs. Can be provided multiple times. \'CPU\' to show all cpus')
    parser.add_argument('--load-avg-thermal-hist', action='append', metavar='PATTERN',
                    help='Same as load-avg-thermal but shows a histogram instead.')
    parser.add_argument('--load-avg', action='append', metavar='PATTERN',
                    help='Show load_avg for CPUs/tasks. Can be provided multiple times. \'CPU\' to show all cpus or specific task name to show all task that match the str')
    parser.add_argument('--load-avg-hist', action='append', metavar='PATTERN',
                    help='Same as load-avg but shows a histogram instead.')
    parser.add_argument('--runnable-avg', action='append', metavar='PATTERN',
                    help='Show runnable_avg for CPUs/tasks. Can be provided multiple times. \'CPU\' to show all cpus or specific task name to show all task that match the str')
    parser.add_argument('--runnable-avg-hist', action='append', metavar='PATTERN',
                    help='Same as runnable-avg but shows a histogram instead.')
    parser.add_argument('--uclamped-avg', action='append', metavar='PATTERN',
                    help='Show uclamped_avg for CPUs/tasks. Can be provided multiple times. \'CPU\' to show all cpus or specific task name to show all task that match the str')
    parser.add_argument('--uclamped-avg-hist', action='append', metavar='PATTERN',
                    help='Same as uclamped-avg but shows a histogram instead.')

    parser.add_argument('--sched-report', action='store_true',
                    help='Print a general summary of sched info for all tasks in the trace.')
    parser.add_argument('--sched-states', action='append', metavar='PATTERN',
                    help='Print a summary of sched-states for a task in the trace. Can be provided multiple times.')
    parser.add_argument('--sched-states-parent', action='append', metavar='PATTERN',
                    help='Print a summary of sched-states for a all tasks belonging to parent in the trace. Can be provided multiple times.')

    parser.add_argument('--cpu-nr-running', action='append',
                    help='Show nr of tasks running for CPUs. Can be provided multiple times. \'CPU\' to show all cpus.')
    parser.add_argument('--cpu-nr-running-hist', action='append', metavar='PATTERN',
                    help='Same as cpu-nr-running but shows a histogram instead.')


    parser.add_argument('--ts-start', type=float,
                    help='Plot starting from this timestamp')
    parser.add_argument('--ts-end', type=float,
                    help='Plot end with this timestamp')
    parser.add_argument('--fig-width-tui', type=int,
                    help='Width of TUI text and figures')
    parser.add_argument('--fig-height-tui', type=int,
                    help='Height of TUI figures')
    parser.add_argument('--xfrequency-tui', type=int,
                    help='Frequency of x-axis of time based TUI figures')

    parser.add_argument('--theme', type=str, default='clear',
                    choices=['default', 'clear', 'pro', 'matrix',
                             'windows', 'girly', 'dark', 'metro',
                             'elegant', 'grandpa', 'salad', 'serious',
                             'scream', 'dreamland', 'sand', 'mature'],
                    help='TUI Color theme.')

    try:
        argcomplete.autocomplete(parser)
    except:
        pass

    return parser.parse_args()

if __name__ == '__main__':
    args = parse_cmdline()

    pltext.clf()
    pltext.cld()
    pltext.theme(args.theme)
    matplotlib.use('Agg')

    prefix = args.filename.replace('.perfetto-trace', '')

    trace = tp.get_trace(args.filename)

    utils.init(trace)

    # Handle settings
    settings.init()
    if args.ts_start:
        settings.set_ts_start(args.ts_start)
    if args.ts_end:
        settings.set_ts_end(args.ts_end)
    if args.fig_width_tui:
        settings.set_fig_width_tui(args.fig_width_tui)
    if args.fig_height_tui:
        settings.set_fig_height_tui(args.fig_height_tui)
    if args.xfrequency_tui:
        settings.set_xfrequncy_tui(args.xfrequency_tui)

    if args.freq or args.freq_residency or args.freq_task or args.freq_residency_task:
        freq.init(trace)
        show_tui = True

        if args.save_csv:
            freq.save_csv(prefix)
            show_tui = False

        if args.freq:
            if (args.save_png):
                freq.plot_matplotlib(pltlib, prefix)
                show_tui = False

            if show_tui:
                freq.plot_tui(pltext)

        if args.freq_residency:
            if (args.save_png):
                freq.plot_residency_matplotlib(pltlib, prefix)
                show_tui = False

            if show_tui:
                freq.plot_residency_tui(pltext)

        if args.freq_task:
            if (args.save_png):
                print("freq-task --save-png: Not implemented yet.")
                show_tui = False

            if show_tui:
                freq.plot_task_tui(pltext, args.freq_task)

        if args.freq_residency_task:
            if (args.save_png):
                print("freq-residency-task --save-png: Not implemented yet.")
                show_tui = False

            if show_tui:
                freq.plot_task_residency_tui(pltext, args.freq_residency_task)

    if args.idle_residency:
        idle.init(trace)
        show_tui = True

        if args.save_csv:
            idle.save_csv(prefix)
            show_tui = False

        if (args.save_png):
            idle.plot_residency_matplotlib(pltlib, prefix)
            show_tui = False

        if show_tui:
            idle.plot_residency_tui(pltext)

    if args.util_avg or args.util_avg_hist:
        sa_track.init(trace, 'util_avg')
        show_tui = True

        if args.save_csv:
            sa_track.sa_track_save_csv(prefix)
            show_tui = False

        if args.util_avg:
            if args.save_png:
                sa_track.plot_sa_track_matplotlib(pltlib, prefix, args.util_avg)
                show_tui = False

            if show_tui:
                sa_track.plot_sa_track_tui(pltext, args.util_avg)

        if args.util_avg_hist:
            if args.save_png:
                sa_track.plot_sa_track_hist_matplotlib(pltlib, prefix, args.util_avg_hist)
                show_tui = False

            if show_tui:
                sa_track.plot_sa_track_hist_tui(pltext, args.util_avg_hist)

    if args.util_avg_rt or args.util_avg_rt_hist:
        sa_track.init(trace, 'util_avg_rt')
        show_tui = True

        if args.save_csv:
            sa_track.sa_track_save_csv(prefix)
            show_tui = False

        if args.util_avg_rt:
            if args.save_png:
                sa_track.plot_sa_track_matplotlib(pltlib, prefix, args.util_avg_rt)
                show_tui = False

            if show_tui:
                sa_track.plot_sa_track_tui(pltext, args.util_avg_rt)

        if args.util_avg_rt_hist:
            if args.save_png:
                sa_track.plot_sa_track_hist_matplotlib(pltlib, prefix, args.util_avg_rt_hist)
                show_tui = False

            if show_tui:
                sa_track.plot_sa_track_hist_tui(pltext, args.util_avg_rt_hist)

    if args.util_avg_dl or args.util_avg_dl_hist:
        sa_track.init(trace, 'util_avg_dl')
        show_tui = True

        if args.save_csv:
            sa_track.sa_track_save_csv(prefix)
            show_tui = False

        if args.util_avg_dl:
            if args.save_png:
                sa_track.plot_sa_track_matplotlib(pltlib, prefix, args.util_avg_dl)
                show_tui = False

            if show_tui:
                sa_track.plot_sa_track_tui(pltext, args.util_avg_dl)

        if args.util_avg_dl_hist:
            if args.save_png:
                sa_track.plot_sa_track_hist_matplotlib(pltlib, prefix, args.util_avg_dl_hist)
                show_tui = False

            if show_tui:
                sa_track.plot_sa_track_hist_tui(pltext, args.util_avg_dl_hist)

    if args.util_avg_irq or args.util_avg_irq_hist:
        sa_track.init(trace, 'util_avg_irq')
        show_tui = True

        if args.save_csv:
            sa_track.sa_track_save_csv(prefix)
            show_tui = False

        if args.util_avg_irq:
            if args.save_png:
                sa_track.plot_sa_track_matplotlib(pltlib, prefix, args.util_avg_irq)
                show_tui = False

            if show_tui:
                sa_track.plot_sa_track_tui(pltext, args.util_avg_irq)

        if args.util_avg_irq_hist:
            if args.save_png:
                sa_track.plot_sa_track_hist_matplotlib(pltlib, prefix, args.util_avg_irq_hist)
                show_tui = False

            if show_tui:
                sa_track.plot_sa_track_hist_tui(pltext, args.util_avg_irq_hist)

    if args.load_avg_thermal or args.load_avg_thermal_hist:
        sa_track.init(trace, 'load_avg_thermal')
        show_tui = True

        if args.save_csv:
            sa_track.sa_track_save_csv(prefix)
            show_tui = False

        if args.load_avg_thermal:
            if args.save_png:
                sa_track.plot_sa_track_matplotlib(pltlib, prefix, args.load_avg_thermal)
                show_tui = False

            if show_tui:
                sa_track.plot_sa_track_tui(pltext, args.load_avg_thermal)

        if args.load_avg_thermal_hist:
            if args.save_png:
                sa_track.plot_sa_track_hist_matplotlib(pltlib, prefix, args.load_avg_thermal_hist)
                show_tui = False

            if show_tui:
                sa_track.plot_sa_track_hist_tui(pltext, args.load_avg_thermal_hist)

    if args.load_avg or args.load_avg_hist:
        sa_track.init(trace, 'load_avg')
        show_tui = True

        if args.save_csv:
            sa_track.sa_track_save_csv(prefix)
            show_tui = False

        if args.load_avg:
            if args.save_png:
                sa_track.plot_sa_track_matplotlib(pltlib, prefix, args.load_avg)
                show_tui = False

            if show_tui:
                sa_track.plot_sa_track_tui(pltext, args.load_avg)

        if args.load_avg_hist:
            if args.save_png:
                sa_track.plot_sa_track_hist_matplotlib(pltlib, prefix, args.load_avg_hist)
                show_tui = False

            if show_tui:
                sa_track.plot_sa_track_hist_tui(pltext, args.load_avg_hist)

    if args.runnable_avg or args.runnable_avg_hist:
        sa_track.init(trace, 'runnable_avg')
        show_tui = True

        if args.save_csv:
            sa_track.sa_track_save_csv(prefix)
            show_tui = False

        if args.runnable_avg:
            if args.save_png:
                sa_track.plot_sa_track_matplotlib(pltlib, prefix, args.runnable_avg)
                show_tui = False

            if show_tui:
                sa_track.plot_sa_track_tui(pltext, args.runnable_avg)

        if args.runnable_avg_hist:
            if args.save_png:
                sa_track.plot_sa_track_hist_matplotlib(pltlib, prefix, args.runnable_avg_hist)
                show_tui = False

            if show_tui:
                sa_track.plot_sa_track_hist_tui(pltext, args.runnable_avg_hist)

    if args.uclamped_avg or args.uclamped_avg_hist:
        sa_track.init(trace, 'uclamped_avg')
        show_tui = True

        if args.save_csv:
            sa_track.sa_track_save_csv(prefix)
            show_tui = False

        if args.uclamped_avg:
            if args.save_png:
                sa_track.plot_sa_track_matplotlib(pltlib, prefix, args.uclamped_avg)
                show_tui = False

            if show_tui:
                sa_track.plot_sa_track_tui(pltext, args.uclamped_avg)

        if args.uclamped_avg_hist:
            if args.save_png:
                sa_track.plot_sa_track_hist_matplotlib(pltlib, prefix, args.uclamped_avg_hist)
                show_tui = False

            if show_tui:
                sa_track.plot_sa_track_hist_tui(pltext, args.uclamped_avg_hist)

    if args.cpu_nr_running or args.cpu_nr_running_hist:
        sa_track.init(trace, 'nr_running')
        show_tui = True

        if args.save_csv:
            sa_track.sa_track_save_csv(prefix)
            show_tui = False

        if args.cpu_nr_running:
            if args.save_png:
                sa_track.plot_sa_track_matplotlib(pltlib, prefix, args.cpu_nr_running)
                show_tui = False

            if show_tui:
                sa_track.plot_sa_track_tui(pltext, args.cpu_nr_running)

        if args.cpu_nr_running_hist:
            if args.save_png:
                sa_track.plot_sa_track_hist_matplotlib(pltlib, prefix, args.cpu_nr_running_hist)
                show_tui = False

            if show_tui:
                sa_track.plot_sa_track_hist_tui(pltext, args.cpu_nr_running_hist)

    if args.sched_report or args.sched_states or args.sched_states_parent:
        sched.init(trace)
        show_tui = True

        if args.save_csv:
            sched.states_save_csv(prefix)
            show_tui = False

        if args.save_png:
            print("sched-* --save-png: Not implemented yet.")
            show_tui = False

        if show_tui:
            if args.sched_report:
                sched.sched_report(pltext)
            if args.sched_states:
                sched.states_summary(pltext, args.sched_states)
            if args.sched_states_parent:
                sched.states_summary_parent(pltext, args.sched_states_parent)

    trace.close()
